print(1 - 2)
print(2.5 + 2.5 - 1.25)
print((10 * 2) / 6)
print(8.5 / (2 * 9) - -3)
print(True == False)
print(True != False)
print((5 < 10))
print((not(5 - 4 > 3 * 2) == (not False)))
print(True and True)
print(False and True)
print((0 < 1) or False)
print(False or False)
